### ISSUE TITLE
[CRASH] Crashed when trying to shift a selection by one tile.

### ISSUE THREAD

**Issue by jarquafelmu** [mickael9/cut-and-paste#5]
My intention was to shift my selection by one tile by shift clicking to force a placement. I see now that potentially my problem was that a build site shared a space with a delete site.

Here's an [image of the error](http://imgur.com/a/Wu8bv).

And this is [what I tried to do](http://imgur.com/a/2QqnI).

I hope that helps.

**Comment by mickael9** [comment]
Thanks for the report. I can't reproduce but I know how to fix it
I don't see how that could happen though. Please let me know if you can reproduce it and provide a save file.
