### ISSUE TITLE
For me it simply doesn't work

### ISSUE THREAD

**Issue by xenadmin** [mickael9/cut-and-paste#6]
I play on win64 and tested Factorio 0.15.10 and 0.15.11.
Every time I try to copy something, I have it attached to my mouse afterwards, but when I click to place it, nothing happens. 

Same with cut. I mark something, it gets marked for deconstruction, I have it attached to my cursor, but when I place it nothing happens. 

Any idea what this is? Should I make a small video?

**Comment by mickael9** [comment]
Nothing happens as in no ghosts are placed at all?

This is what should happen:
![](https://mods-data.factorio.com/pub_data/media_files/3k2gtIPhUmPm.gif)

The final building step is achieved by construction robots, just like if you'd place a blueprint

If you have working construction robots and it works with normal blueprints then it might be an incompatibility issue with another mod. What mods do you have?

**Comment by xenadmin** [comment]
> Nothing happens as in no ghosts are placed at all?

Exactly!

- AutoDeconstruct_0.1.8
- auto-research_3.3.1
- Big_Brother_0.4.3
- Bottleneck_0.7.1
- Crafting_Speed_Research_0.1.5
- cut-and-paste_0.1.2
- EvoGUI_0.4.202
- expanded_tools_1.0.4
- FARL_1.0.5
- folk-fill_0.2.1
- folk-justgo_0.2.2
- folk-shuttle_0.1.12
- Honk_2.1.3
- long-loot-research_0.2.1
- long-mine-research_0.2.1
- long-pickup-research_0.2.1
- long-reach-research_0.3.1
- Orbital Ion Cannon_1.5.0
- Squeak Through_1.1.7
- WaterWell_1.0.18

**Comment by mickael9** [comment]
I just tried with your mod list in a new save and it seems to work fine (the ghosts are correctly placed).
Can you reproduce the issue with a new save? If not, can you share your save file so I can investigate further?

Just to be clear, does this happens all the time even for the simplest things like moving a single furnace to another location (without conflicting entities or stuff like that)?

**Comment by xenadmin** [comment]
Here is the save:
https://files.meinekleinefarm.net/f/898b7f78b1/

> Just to be clear, does this happens all the time even for the simplest things like moving a single furnace to another location (without conflicting entities or stuff like that)?

Yes

I make a Video if you like?

New Mods List:

- AutoDeconstruct_0.1.8
- auto-research_3.3.1
- Big_Brother_0.4.3
- Blueprint Items Request_0.1.4
- Bottleneck_0.7.2
- Crafting_Speed_Research_0.1.5
- cut-and-paste_0.1.2
- EquipmentHotkeys_0.0.2
- EvoGUI_0.4.202
- expanded_tools_1.0.4
- FARL_1.0.8
- folk-fill_0.2.1
- folk-justgo_0.2.2
- folk-shuttle_0.1.12
- folk-stopthat_0.1.2
- helmod_0.5.2
- Honk_2.1.3
- long-reach-research_0.4.0
- Orbital Ion Cannon_1.5.1
- Squeak Through_1.1.7
- upgrade-planner_1.2.18
- WaterWell_1.0.18

**Comment by mickael9** [comment]
Thanks, I found the problem now :+1:
